server:
  port: 8761
eureka:
  instance:
    hostname: localhost

#  client:
#    service-url:
#      defaultNone: http://${eureka.instance.hostname}:${server.port}/eureka
#    register-with-eureka: false
#    fetch-registry: false
spring:
  application:
    name: demo_test
