server:
  port: 9000

eureka:
  instance:
    hostname: localhost

  client:
    service-url:
      defaultNone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: eureka-consumer